//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.SDFAuth
{
    using System;
    using System.Collections.Generic;
    
    using DataBase;
    public partial class S_District :BaseEntity
    {
        public S_District()
        {
            this.UserCity = new HashSet<UserCity>();
        }
    
        public long DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<long> CityID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<UserCity> UserCity { get; set; }
    }
}
